/**
 * Tunnelbot - OpenAPI 3.0
 * This is the API specification for the tunnelbot backend.
 *
 * The version of the OpenAPI document: 1
 * Contact: info@farmersandrobots.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class DeviceCategory.
* @enum {}
* @readonly
*/
export default class DeviceCategory {
    
        /**
         * value: "curtain"
         * @const
         */
        "curtain" = "curtain";

    
        /**
         * value: "heating"
         * @const
         */
        "heating" = "heating";

    
        /**
         * value: "irrigation"
         * @const
         */
        "irrigation" = "irrigation";

    
        /**
         * value: "weather"
         * @const
         */
        "weather" = "weather";

    
        /**
         * value: "lighting"
         * @const
         */
        "lighting" = "lighting";

    
        /**
         * value: "fan"
         * @const
         */
        "fan" = "fan";

    
        /**
         * value: "other"
         * @const
         */
        "other" = "other";

    

    /**
    * Returns a <code>DeviceCategory</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/DeviceCategory} The enum <code>DeviceCategory</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

