/**
 * Tunnelbot - OpenAPI 3.0
 * This is the API specification for the tunnelbot backend.
 *
 * The version of the OpenAPI document: 1
 * Contact: info@farmersandrobots.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Role from './Role';

/**
 * The FarmAssociation model module.
 * @module model/FarmAssociation
 * @version 1
 */
class FarmAssociation {
    /**
     * Constructs a new <code>FarmAssociation</code>.
     * @alias module:model/FarmAssociation
     */
    constructor() { 
        
        FarmAssociation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FarmAssociation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FarmAssociation} obj Optional instance to populate.
     * @return {module:model/FarmAssociation} The populated <code>FarmAssociation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FarmAssociation();

            if (data.hasOwnProperty('farmId')) {
                obj['farmId'] = ApiClient.convertToType(data['farmId'], 'Number');
            }
            if (data.hasOwnProperty('farmName')) {
                obj['farmName'] = ApiClient.convertToType(data['farmName'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = Role.constructFromObject(data['role']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FarmAssociation</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FarmAssociation</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['farmName'] && !(typeof data['farmName'] === 'string' || data['farmName'] instanceof String)) {
            throw new Error("Expected the field `farmName` to be a primitive type in the JSON string but got " + data['farmName']);
        }

        return true;
    }


}



/**
 * @member {Number} farmId
 */
FarmAssociation.prototype['farmId'] = undefined;

/**
 * @member {String} farmName
 */
FarmAssociation.prototype['farmName'] = undefined;

/**
 * @member {module:model/Role} role
 */
FarmAssociation.prototype['role'] = undefined;






export default FarmAssociation;

