/**
 * Tunnelbot - OpenAPI 3.0
 * This is the API specification for the tunnelbot backend.
 *
 * The version of the OpenAPI document: 1
 * Contact: info@farmersandrobots.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Tunnel model module.
 * @module model/Tunnel
 * @version 1
 */
class Tunnel {
    /**
     * Constructs a new <code>Tunnel</code>.
     * @alias module:model/Tunnel
     * @param name {String} 
     */
    constructor(name) { 
        
        Tunnel.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>Tunnel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Tunnel} obj Optional instance to populate.
     * @return {module:model/Tunnel} The populated <code>Tunnel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Tunnel();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('kind')) {
                obj['kind'] = ApiClient.convertToType(data['kind'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('deviceIds')) {
                obj['deviceIds'] = ApiClient.convertToType(data['deviceIds'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Tunnel</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Tunnel</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Tunnel.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['kind'] && !(typeof data['kind'] === 'string' || data['kind'] instanceof String)) {
            throw new Error("Expected the field `kind` to be a primitive type in the JSON string but got " + data['kind']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['deviceIds'])) {
            throw new Error("Expected the field `deviceIds` to be an array in the JSON data but got " + data['deviceIds']);
        }

        return true;
    }


}

Tunnel.RequiredProperties = ["name"];

/**
 * @member {Number} id
 */
Tunnel.prototype['id'] = undefined;

/**
 * @member {String} kind
 */
Tunnel.prototype['kind'] = undefined;

/**
 * @member {String} name
 */
Tunnel.prototype['name'] = undefined;

/**
 * @member {Array.<Number>} deviceIds
 */
Tunnel.prototype['deviceIds'] = undefined;






export default Tunnel;

