/**
 * Tunnelbot - OpenAPI 3.0
 * This is the API specification for the tunnelbot backend.
 *
 * The version of the OpenAPI document: 1
 * Contact: info@farmersandrobots.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TunnelbotOpenApi30);
  }
}(this, function(expect, TunnelbotOpenApi30) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TunnelbotOpenApi30.FarmApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FarmApi', function() {
    describe('addFarm', function() {
      it('should call addFarm successfully', function(done) {
        //uncomment below and update the code to test addFarm
        //instance.addFarm(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addPerson', function() {
      it('should call addPerson successfully', function(done) {
        //uncomment below and update the code to test addPerson
        //instance.addPerson(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteFarm', function() {
      it('should call deleteFarm successfully', function(done) {
        //uncomment below and update the code to test deleteFarm
        //instance.deleteFarm(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('findFarmByName', function() {
      it('should call findFarmByName successfully', function(done) {
        //uncomment below and update the code to test findFarmByName
        //instance.findFarmByName(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getFarmById', function() {
      it('should call getFarmById successfully', function(done) {
        //uncomment below and update the code to test getFarmById
        //instance.getFarmById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('removePerson', function() {
      it('should call removePerson successfully', function(done) {
        //uncomment below and update the code to test removePerson
        //instance.removePerson(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateFarm', function() {
      it('should call updateFarm successfully', function(done) {
        //uncomment below and update the code to test updateFarm
        //instance.updateFarm(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
