/**
 * Tunnelbot - OpenAPI 3.0
 * This is the API specification for the tunnelbot backend.
 *
 * The version of the OpenAPI document: 1
 * Contact: info@farmersandrobots.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TunnelbotOpenApi30);
  }
}(this, function(expect, TunnelbotOpenApi30) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TunnelbotOpenApi30.TunnelApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TunnelApi', function() {
    describe('addTunnel', function() {
      it('should call addTunnel successfully', function(done) {
        //uncomment below and update the code to test addTunnel
        //instance.addTunnel(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteTunnel', function() {
      it('should call deleteTunnel successfully', function(done) {
        //uncomment below and update the code to test deleteTunnel
        //instance.deleteTunnel(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTunnelById', function() {
      it('should call getTunnelById successfully', function(done) {
        //uncomment below and update the code to test getTunnelById
        //instance.getTunnelById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTunnels', function() {
      it('should call getTunnels successfully', function(done) {
        //uncomment below and update the code to test getTunnels
        //instance.getTunnels(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateTunnel', function() {
      it('should call updateTunnel successfully', function(done) {
        //uncomment below and update the code to test updateTunnel
        //instance.updateTunnel(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
