/*
 * Tunnelbot - OpenAPI 3.0
 * This is the API specification for the tunnelbot backend.
 *
 * OpenAPI spec version: 1
 * Contact: info@farmersandrobots.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../api/ApiClient";
import { Device } from "./Device";

/**
 * The devices model module.
 * @module model/Devices
 * @version 1
 */
export class Devices extends Array {
  /**
   * Constructs a new <code>devices</code>.
   * @alias module:model/devices
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>devices</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Devices} obj Optional instance to populate.
   * @return {module:model/Devices} The populated <code>devices</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Devices();
      ApiClient.constructFromObject(data, obj, "Device");
    }
    return obj;
  }
}
