/*
 * Tunnelbot - OpenAPI 3.0
 * This is the API specification for the tunnelbot backend.
 *
 * OpenAPI spec version: 1
 * Contact: info@farmersandrobots.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../api/ApiClient";
import { DeviceCategory } from "./DeviceCategory";

/**
 * The Device model module.
 * @module model/Device
 * @version 1
 */
export class Device {
  /**
   * Constructs a new <code>Device</code>.
   * @alias module:model/Device
   * @class
   * @param name {String}
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>Device</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Device} obj Optional instance to populate.
   * @return {module:model/Device} The populated <code>Device</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Device();
      if (data.hasOwnProperty("id"))
        obj.id = ApiClient.convertToType(data["id"], "Number");
      if (data.hasOwnProperty("kind"))
        obj.kind = ApiClient.convertToType(data["kind"], "String");
      if (data.hasOwnProperty("name"))
        obj.name = ApiClient.convertToType(data["name"], "String");
      if (data.hasOwnProperty("category"))
        obj.category = DeviceCategory.constructFromObject(data["category"]);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Device.prototype.id = undefined;

/**
 * @member {String} kind
 */
Device.prototype.kind = undefined;

/**
 * @member {String} name
 */
Device.prototype.name = undefined;

/**
 * @member {module:model/DeviceCategory} category
 */
Device.prototype.category = undefined;
