/*
 * Tunnelbot - OpenAPI 3.0
 * This is the API specification for the tunnelbot backend.
 *
 * OpenAPI spec version: 1
 * Contact: info@farmersandrobots.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../api/ApiClient";
import { Role } from "./Role";

/**
 * The PersonAssociation model module.
 * @module model/PersonAssociation
 * @version 1
 */
export class PersonAssociation {
  /**
   * Constructs a new <code>PersonAssociation</code>.
   * @alias module:model/PersonAssociation
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>PersonAssociation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PersonAssociation} obj Optional instance to populate.
   * @return {module:model/PersonAssociation} The populated <code>PersonAssociation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PersonAssociation();
      if (data.hasOwnProperty("personId"))
        obj.personId = ApiClient.convertToType(data["personId"], "Number");
      if (data.hasOwnProperty("displayName"))
        obj.displayName = ApiClient.convertToType(
          data["displayName"],
          "String",
        );
      if (data.hasOwnProperty("email"))
        obj.email = ApiClient.convertToType(data["email"], "String");
      if (data.hasOwnProperty("role"))
        obj.role = Role.constructFromObject(data["role"]);
    }
    return obj;
  }
}

/**
 * @member {Number} personId
 */
PersonAssociation.prototype.personId = undefined;

/**
 * @member {String} displayName
 */
PersonAssociation.prototype.displayName = undefined;

/**
 * @member {String} email
 */
PersonAssociation.prototype.email = undefined;

/**
 * @member {module:model/Role} role
 */
PersonAssociation.prototype.role = undefined;
