/*
 * Tunnelbot - OpenAPI 3.0
 * This is the API specification for the tunnelbot backend.
 *
 * OpenAPI spec version: 1
 * Contact: info@farmersandrobots.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../api/ApiClient";
import { FarmAssociation } from "./FarmAssociation";

/**
 * The Person model module.
 * @module model/Person
 * @version 1
 */
export class Person {
  /**
   * Constructs a new <code>Person</code>.
   * @alias module:model/Person
   * @class
   */
  constructor() {}

  /**
   * Constructs a <code>Person</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Person} obj Optional instance to populate.
   * @return {module:model/Person} The populated <code>Person</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Person();
      if (data.hasOwnProperty("id"))
        obj.id = ApiClient.convertToType(data["id"], "Number");
      if (data.hasOwnProperty("kind"))
        obj.kind = ApiClient.convertToType(data["kind"], "String");
      if (data.hasOwnProperty("displayName"))
        obj.displayName = ApiClient.convertToType(
          data["displayName"],
          "String",
        );
      if (data.hasOwnProperty("firstName"))
        obj.firstName = ApiClient.convertToType(data["firstName"], "String");
      if (data.hasOwnProperty("lastName"))
        obj.lastName = ApiClient.convertToType(data["lastName"], "String");
      if (data.hasOwnProperty("email"))
        obj.email = ApiClient.convertToType(data["email"], "String");
      if (data.hasOwnProperty("phone"))
        obj.phone = ApiClient.convertToType(data["phone"], "String");
      if (data.hasOwnProperty("farmAssociations"))
        obj.farmAssociations = ApiClient.convertToType(
          data["farmAssociations"],
          [FarmAssociation],
        );
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Person.prototype.id = undefined;

/**
 * @member {String} kind
 */
Person.prototype.kind = undefined;

/**
 * @member {String} displayName
 */
Person.prototype.displayName = undefined;

/**
 * @member {String} firstName
 */
Person.prototype.firstName = undefined;

/**
 * @member {String} lastName
 */
Person.prototype.lastName = undefined;

/**
 * @member {String} email
 */
Person.prototype.email = undefined;

/**
 * @member {String} phone
 */
Person.prototype.phone = undefined;

/**
 * @member {Array.<module:model/FarmAssociation>} farmAssociations
 */
Person.prototype.farmAssociations = undefined;
