/*
 * Tunnelbot - OpenAPI 3.0
 * This is the API specification for the tunnelbot backend.
 *
 * OpenAPI spec version: 1
 * Contact: info@farmersandrobots.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import { ApiClient } from "../api/ApiClient";

/**
 * Enum class Role.
 * @enum {String}
 * @readonly
 */
const Role = {
  /**
   * value: "worker"
   * @const
   */
  worker: "worker",

  /**
   * value: "admin"
   * @const
   */
  admin: "admin",

  /**
   * value: "owner"
   * @const
   */
  owner: "owner",

  /**
   * Returns a <code>Role</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/Role} The enum <code>Role</code> value.
   */
  constructFromObject: function (object) {
    return object;
  },
};

export { Role };
