/*
 * Tunnelbot - OpenAPI 3.0
 * This is the API specification for the tunnelbot backend.
 *
 * OpenAPI spec version: 1
 * Contact: info@farmersandrobots.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Role} from './Role';

/**
 * The FarmAssociation model module.
 * @module model/FarmAssociation
 * @version 1
 */
export class FarmAssociation {
  /**
   * Constructs a new <code>FarmAssociation</code>.
   * @alias module:model/FarmAssociation
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FarmAssociation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FarmAssociation} obj Optional instance to populate.
   * @return {module:model/FarmAssociation} The populated <code>FarmAssociation</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FarmAssociation();
      if (data.hasOwnProperty('farmId'))
        obj.farmId = ApiClient.convertToType(data['farmId'], 'Number');
      if (data.hasOwnProperty('farmName'))
        obj.farmName = ApiClient.convertToType(data['farmName'], 'String');
      if (data.hasOwnProperty('role'))
        obj.role = Role.constructFromObject(data['role']);
    }
    return obj;
  }
}

/**
 * @member {Number} farmId
 */
FarmAssociation.prototype.farmId = undefined;

/**
 * @member {String} farmName
 */
FarmAssociation.prototype.farmName = undefined;

/**
 * @member {module:model/Role} role
 */
FarmAssociation.prototype.role = undefined;

