/*
 * Tunnelbot - OpenAPI 3.0
 * This is the API specification for the tunnelbot backend.
 *
 * OpenAPI spec version: 1
 * Contact: info@farmersandrobots.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Address} from './Address';
import {PersonAssociation} from './PersonAssociation';

/**
 * The Farm model module.
 * @module model/Farm
 * @version 1
 */
export class Farm {
  /**
   * Constructs a new <code>Farm</code>.
   * @alias module:model/Farm
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Farm</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Farm} obj Optional instance to populate.
   * @return {module:model/Farm} The populated <code>Farm</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Farm();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('kind'))
        obj.kind = ApiClient.convertToType(data['kind'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('createDate'))
        obj.createDate = ApiClient.convertToType(data['createDate'], 'Date');
      if (data.hasOwnProperty('address'))
        obj.address = Address.constructFromObject(data['address']);
      if (data.hasOwnProperty('owners'))
        obj.owners = ApiClient.convertToType(data['owners'], [PersonAssociation]);
      if (data.hasOwnProperty('people'))
        obj.people = ApiClient.convertToType(data['people'], [PersonAssociation]);
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Farm.prototype.id = undefined;

/**
 * @member {String} kind
 */
Farm.prototype.kind = undefined;

/**
 * @member {String} name
 */
Farm.prototype.name = undefined;

/**
 * @member {Date} createDate
 */
Farm.prototype.createDate = undefined;

/**
 * @member {module:model/Address} address
 */
Farm.prototype.address = undefined;

/**
 * @member {Array.<module:model/PersonAssociation>} owners
 */
Farm.prototype.owners = undefined;

/**
 * @member {Array.<module:model/PersonAssociation>} people
 */
Farm.prototype.people = undefined;

