/*
 * Tunnelbot - OpenAPI 3.0
 * This is the API specification for the tunnelbot backend.
 *
 * OpenAPI spec version: 1
 * Contact: info@farmersandrobots.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Tunnel} from './Tunnel';

/**
 * The Tunnels model module.
 * @module model/Tunnels
 * @version 1
 */
export class Tunnels extends Array {
  /**
   * Constructs a new <code>Tunnels</code>.
   * @alias module:model/Tunnels
   * @class
   * @extends Array
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>Tunnels</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Tunnels} obj Optional instance to populate.
   * @return {module:model/Tunnels} The populated <code>Tunnels</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Tunnels();
      ApiClient.constructFromObject(data, obj, 'Tunnel');
    }
    return obj;
  }
}
