/*
 * Tunnelbot - OpenAPI 3.0
 * This is the API specification for the tunnelbot backend.
 *
 * OpenAPI spec version: 1
 * Contact: info@farmersandrobots.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.51
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Tunnel model module.
 * @module model/Tunnel
 * @version 1
 */
export class Tunnel {
  /**
   * Constructs a new <code>Tunnel</code>.
   * @alias module:model/Tunnel
   * @class
   * @param name {String} 
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>Tunnel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Tunnel} obj Optional instance to populate.
   * @return {module:model/Tunnel} The populated <code>Tunnel</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Tunnel();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('kind'))
        obj.kind = ApiClient.convertToType(data['kind'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} id
 */
Tunnel.prototype.id = undefined;

/**
 * @member {String} kind
 */
Tunnel.prototype.kind = undefined;

/**
 * @member {String} name
 */
Tunnel.prototype.name = undefined;

